// Code generated by "stringer -type=State"; DO NOT EDIT.

package node

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Joining-1]
	_ = x[Ready-2]
	_ = x[Leaving-3]
}

const _NodeState_name = "NodeUndefinedNodeJoiningNodeReadyNodeLeaving"

var _NodeState_index = [...]uint8{0, 13, 24, 33, 44}

func (i State) String() string {
	if i >= State(len(_NodeState_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeState_name[_NodeState_index[i]:_NodeState_index[i+1]]
}
