apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
bases:
  - ../aks
patchesStrategicMerge:
  - patch-virtual.yaml
  - patch-Ingress.yaml
  - patch-wait-script.yaml
  - patch-certs-pvc.yaml
