ignore:
  - "**/*_mock.go"
  - "**/*_string.go"
  - "**/*.pb.go"
fixes:
  - "github.com/insolar/assured-ledger/::"
coverage:
  status:
    project:
      default:
        threshold: 1%
github_checks:
  annotations: false
