version: 2
mergeable:
  - when: schedule.repository
    validate:
      - do: stale
        days: 30
        type: pull_request
    pass:
      - do: comment
        payload:
          body: 'This pull request is old. Please consider merging or closing it.'

  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_exclude:
          regex: '\bWIP\b'
        must_include:
          regex: '^([A-Z][A-Z]+-\d+|NOISSUE|HOTFIX):'
          regex_flag: none
      - do: description
        no_empty:
          enabled: true
          message: 'Description matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.'
      - do: approvals
        min:
          count: 2
          message: 'A minimum of 2 approvals required.'
        required:
          assignees: true
          message: 'All assignees must approve this PR before merging.'
        block:
          changes_requested: true
          message: 'Merge is blocked, changes requested.'
        limit:
          teams: ['insolar/dev-core']
