# the high level policy
policy:
  approval:
    - "the core team has approved"
  disapproval:
    options:
      methods:
        disapprove:
          github_review: true
        revoke:
          comments:
          github_review: true
    requires:
      organizations:
        - "insolar"

# the list of rules
approval_rules:
  - name: "the core team has approved"
    options:
      invalidate_on_push: true
      ignore_update_merges: true
      methods:
        github_review: true
    requires:
      count: 2
      teams:
        - "insolar/dev-core"
