status = [
    "checks",
    "pre-build-check",
    "windows-checks"
]
pr_status = [
    "checks",
    "pre-build-check",
    "windows-checks"
]
block_labels = [
    "WIP", "wip",
    "DONOTMERGE", "donotmerge",
    "DRAFT", "draft"
]
timeout_sec = 7200
required_approvals = 1
delete_merged_branches = true
use_squash_merge = true
