host:
  transport:
    protocol: TCP
    address: 127.0.0.1:0
    fixedpublicaddress: ""
  mintimeout: 10
  maxtimeout: 2000
  timeoutmult: 2
  signmessages: false
  handshakesessionttl: 5000
  pulsewatchdogtimeout: 2592000
service:
  cachedirectory: network_cache
ledger:
  lightchainlimit: 5
log:
  level: Debug
  adapter: zerolog
  formatter: json
  outputtype: stderr
  outputparallellimit: ""
  outputparams: ""
  buffersize: 0
  llbuffersize: 0
metrics:
  listenaddress: 0.0.0.0:9091
  namespace: placeholder
  zpagesenabled: true
  reportingperiod: 0s
logicrunner:
  rpclisten: 0.0.0.0:33315
  rpcprotocol: tcp
  goplugin:
    runnerlisten: 0.0.0.0:33314
    runnerprotocol: tcp
  pulselrusize: 100
apirunner:
  address: localhost:19101
  rpc: /api/rpc
  isadmin: false
  swaggerpath: /app/api-exported.yaml
adminapirunner:
  address: 0.0.0.0:19001
  rpc: /admin-api/rpc
  isadmin: true
  swaggerpath: /app/api-exported.yaml
testwalletapi:
  address: 0.0.0.0:32303
availabilitychecker:
  enabled: false
  keeperurl: ""
  requesttimeout: 15
  checkperiod: 5
tracer:
  jaeger:
    collectorendpoint: ""
    agentendpoint: ""
    probabilityrate: 1
  samplingrules: {}
introspection:
  addr: 0.0.0.0:55503
