@startuml
state "GetInitStateFor" as T00_S001
T00_S001 : antiqueEventSM
[*] --> T00_S001
T00_S001 --> T00_S002
state "stepGotAnswer" as T00_S004
T00_S004 : antiqueEventSM
state "DYNAMIC createFn" as T00_U001
T00_U001 : antiqueEventSM
T00_U001 : UNKNOWN 
T00_S004 --> T00_U001 : [cps!=nil]
T00_S004 --> [*] : Error
state "stepInit" as T00_S002
T00_S002 : antiqueEventSM
T00_S002 --> T00_S003
state "stepRequestOldPulseData" as T00_S003
T00_S003 : antiqueEventSM
T00_S003 --> T00_S004
@enduml
