apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "placeholder"
generatorOptions:
  disableNameSuffixHash: true
resources:
  - 0-Namespace.yaml
  - whoami.yaml
  - patch-Ingress.yaml
