@startuml
Init : INHERITED
Init --> stepProcess : Jump
stepProcess : INHERITED
stepProcess --> stepWaitObjectReady : Jump
stepWaitObjectReady : INHERITED
stepWaitObjectReady --> stepProcessRequest : Jump
stepWaitObjectReady --> stepWaitObjectReady : ThenRepeat
stepWaitObjectReady --> stepWaitObjectReady : ThenRepeat
stepProcessRequest : INHERITED
stepProcessRequest --> stepBuildResponse : Jump
stepProcessRequest --> stepProcessRequest : ThenRepeat
stepBuildResponse : INHERITED
stepBuildResponse --> [*]
@enduml
