@startuml
Init : INHERITED
Init --> stepGetObject : Jump
stepGetObject : INHERITED
stepGetObject --> stepGetObject : ThenRepeat
stepGetObject --> awaitObjectReady : Jump
awaitObjectReady : INHERITED
awaitObjectReady --> awaitObjectReady : ThenRepeat
awaitObjectReady --> stepProcess : Jump
stepProcess : INHERITED
stepProcess --> stepProcess : ThenRepeat
stepProcess --> [*]
@enduml
