@startuml
state "Init" as T01_S001
T01_S001 : SubSMRegister
[*] --> T01_S001
T01_S001 --> T01_S007 : [...&&isConstructor()&&s.Object.IsEmpty()]\nMigrate: Init.1
T01_S001 --> T01_S008 : [s.Incoming!=nil]\nMigrate: Init.2
T01_S001 --> T01_S010 : [s.OutgoingResult!=nil]\nMigrate: Init.3
T01_S001 --> T01_S009 : [s.Outgoing!=nil]\nMigrate: Init.4
T01_S001 --> T01_S011 : [s.IncomingResult!=nil]\nMigrate: Init.5
state "Init.1" as T01_S002
T01_S002 : SubSMRegister
T01_S002 --[dotted]> T01_S002
T01_S002 --> [*]
state "Init.2" as T01_S003
T01_S003 : SubSMRegister
T01_S003 --[dotted]> T01_S003
T01_S003 --> [*]
state "Init.3" as T01_S004
T01_S004 : SubSMRegister
T01_S004 --[dotted]> T01_S004
T01_S004 --> [*]
state "Init.4" as T01_S005
T01_S005 : SubSMRegister
T01_S005 --[dotted]> T01_S005
T01_S005 --> [*]
state "Init.5" as T01_S006
T01_S006 : SubSMRegister
T01_S006 --[dotted]> T01_S006
T01_S006 --> [*]
state "s.messageSender" as T01_S014 <<sdlreceive>>
state "stepRegisterIncoming" as T01_S008
T01_S008 : SubSMRegister
T01_S008 --[dotted]> T01_S003
T01_S008 --> [*] : [err!=nil]\nError
T01_S008 --> T01_S009 : [s.Outgoing!=nil]
T01_S008 --> T01_S011 : [s.IncomingResult!=nil]
state "stepRegisterIncomingResult" as T01_S011
T01_S011 : SubSMRegister
T01_S011 --[dotted]> T01_S003
T01_S011 --[dotted]> T01_S006
T01_S011 --> [*] : [err!=nil]\nError
T01_S011 --> [*] : [err!=nil]\nError
T01_S011 --> [*] : [err!=nil]\nError
T01_S011 --> T01_S012
state "stepRegisterLifeline" as T01_S007
T01_S007 : SubSMRegister
T01_S007 --[dotted]> T01_S002
T01_S007 --> [*] : [err!=nil]\nError
T01_S007 --> T01_S012
state "stepRegisterOutgoing" as T01_S009
T01_S009 : SubSMRegister
T01_S009 --[dotted]> T01_S003
T01_S009 --[dotted]> T01_S005
T01_S009 --> [*] : [err!=nil]\nError
T01_S009 --> T01_S012
state "stepRegisterOutgoingResult" as T01_S010
T01_S010 : SubSMRegister
T01_S010 --[dotted]> T01_S004
T01_S010 --> [*] : [err!=nil]\nError
T01_S010 --> T01_S012
state "stepSaveSafeCounter" as T01_S012
T01_S012 : SubSMRegister
T01_S012 --[dotted]> T01_S002
T01_S012 --[dotted]> T01_S003
T01_S012 --[dotted]> T01_S004
T01_S012 --[dotted]> T01_S005
T01_S012 --[dotted]> T01_S006
T01_S012 --> T01_S012 : [!stateUpdate.IsEmpty()]
T01_S012 --> T01_S013
state "stepSendMessage" as T01_S013
T01_S013 : SubSMRegister
T01_S013 --[dotted]> T01_S002
T01_S013 --[dotted]> T01_S003
T01_S013 --[dotted]> T01_S004
T01_S013 --[dotted]> T01_S005
T01_S013 --[dotted]> T01_S006
T01_S013 --> [*] : [msg==nil]
T01_S013 --> T01_S014 : PrepareAsync(ctx)
T01_S013 --> T01_S015
state "stepWaitResponse" as T01_S015
T01_S015 : SubSMRegister
T01_S015 --[dotted]> T01_S002
T01_S015 --[dotted]> T01_S003
T01_S015 --[dotted]> T01_S004
T01_S015 --[dotted]> T01_S005
T01_S015 --[dotted]> T01_S006
T01_S015 --> [*] : [s.sendError!=nil]\nError
T01_S015 --[dashed]> T01_S015 : [!(...).CurrentSentMessage().ResultReceived()]\nSleep
T01_S015 --> T01_S013
state "GetInitStateFor" as T00_S001
T00_S001 : dSubSMRegister
[*] --> T00_S001
state "nil" as T00_U001
T00_U001 : dSubSMRegister
T00_U001 : UNKNOWN 
T00_S001 --> T00_U001
@enduml
