---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers: []
  name: certs-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers: []
  name: keys-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
