---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pulsar
spec:
  selector:
    matchLabels:
      app: pulsar
  replicas: 1
  serviceName: platform-network
  template:
    metadata:
      annotations:
        prometheus.io/port: "8001"
        prometheus.io/scrape: "true"
      labels:
        app: pulsar
        role: pulsar
        scope: platform
    spec:
      serviceAccountName: insolar-bootstrap
      initContainers:
        - name: wait
          image: "insolar/kubectl:1.18.0"
          command: ["/bin/wait-for-bootstrap.sh"]
          volumeMounts:
            - name: wait-script
              mountPath: /bin/wait-for-bootstrap.sh
              readOnly: true
              subPath: wait-for-bootstrap.sh
      containers:
        - name: pulsar
          image: insolar/assured-ledger:latest
          imagePullPolicy: IfNotPresent
          command: ["pulsard"]
          args: ["--config", "/etc/pulsar/pulsard.yaml"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INSOLAR_KEYSPATH
              value: /etc/insolar/keys/$(NODENAME).json
            - name: INSOLAR_PULSAR_DISTRIBUTIONTRANSPORT_ADDRESS
              value: "$(POD_IP):58091"
          ports:
            - containerPort: 58091
              name: pulsar
          volumeMounts:
            - name: pulsar-config
              mountPath: /etc/pulsar
              readOnly: true
            - name: node-keys
              mountPath: /etc/insolar/keys
              readOnly: true
      volumes:
        - name: pulsar-config
          configMap:
            name: pulsar-config
        - name: node-keys
          secret:
            secretName: node-keys
        - name: wait-script
          configMap:
            defaultMode: 0550
            name: wait-script
