apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "insolar"
patchesStrategicMerge:
  - nodes-patch.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - 0-Namespace.yaml
  - 0-certs-pvc.yaml
  - 1-bootstrap.yaml
  - 2-platform-network-Service.yaml
  - 3-pulsar.yaml
  - 3-pulsewatcher.yaml
  - 3-virtual.yaml
  - 4-ingress.yaml
configMapGenerator:
  - name: bootstrap-yaml
    files:
      - bootstrap.yaml=configuration/bootstrap-config.yaml
  - name: app-bootstrap
    files:
      - run.sh=configuration/bootstrap.sh
  - name: virtual-config
    files:
      - virtual-config.yaml=configuration/virtual-config.yaml
  - name: pulsar-config
    files:
      - pulsard.yaml=configuration/pulsar-config.yaml
  - name: pulsewatcher-config
    files:
      - pulsewatcher.yaml=configuration/pulsewatcher-config.yaml