// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto_vnvn.proto

package rms

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/insolar/assured-ledger/ledger-core/v2/insproto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MessageExample struct {
	RecordExample `protobuf:"bytes,17,opt,name=Record,proto3,embedded=Record" json:"Record"`
	// Add here custom fields
	MsgParam uint64 `protobuf:"varint,1800,opt,name=MsgParam,proto3" json:"MsgParam"`
	MsgBytes string `protobuf:"bytes,1801,opt,name=MsgBytes,proto3" json:"MsgBytes"`
}

func (m *MessageExample) Reset()         { *m = MessageExample{} }
func (m *MessageExample) String() string { return proto.CompactTextString(m) }
func (*MessageExample) ProtoMessage()    {}
func (*MessageExample) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc353dc03c844eae, []int{0}
}
func (m *MessageExample) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessageExample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *MessageExample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageExample.Merge(m, src)
}
func (m *MessageExample) XXX_Size() int {
	return m.ProtoSize()
}
func (m *MessageExample) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageExample.DiscardUnknown(m)
}

var xxx_messageInfo_MessageExample proto.InternalMessageInfo

func (m *MessageExample) GetMsgParam() uint64 {
	if m != nil {
		return m.MsgParam
	}
	return 0
}

func (m *MessageExample) GetMsgBytes() string {
	if m != nil {
		return m.MsgBytes
	}
	return ""
}

func (m *MessageExample_Head) Reset()         { *m = MessageExample_Head{} }
func (m *MessageExample_Head) String() string { return proto.CompactTextString(m) }
func (*MessageExample_Head) ProtoMessage()    {}
func (*MessageExample_Head) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc353dc03c844eae, []int{0, 0}
}
func (m *MessageExample_Head) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessageExample_Head) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *MessageExample_Head) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageExample_Head.Merge(m, src)
}
func (m *MessageExample_Head) XXX_Size() int {
	return m.ProtoSize()
}
func (m *MessageExample_Head) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageExample_Head.DiscardUnknown(m)
}

var xxx_messageInfo_MessageExample_Head proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MessageExample)(nil), "rms.MessageExample")
	proto.RegisterType((*MessageExample_Head)(nil), "rms.MessageExample.Head")
}

func init() { proto.RegisterFile("proto_vnvn.proto", fileDescriptor_fc353dc03c844eae) }

var fileDescriptor_fc353dc03c844eae = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xb1, 0xcb, 0xd3, 0x40,
	0x18, 0xc6, 0x73, 0x36, 0x7e, 0xa6, 0xf9, 0xa0, 0xf4, 0xcb, 0x67, 0x21, 0x74, 0xb8, 0xab, 0xba,
	0x74, 0x69, 0x03, 0x75, 0xeb, 0x66, 0x8a, 0x20, 0x85, 0x82, 0x44, 0x77, 0xb9, 0xb6, 0xe7, 0x35,
	0xd0, 0xe4, 0xca, 0x5d, 0x5a, 0xda, 0xff, 0xa0, 0x3a, 0x09, 0x82, 0xd0, 0x4e, 0x71, 0x2b, 0x8e,
	0xfe, 0x05, 0x8e, 0x1d, 0x3b, 0x66, 0x90, 0xa2, 0xc9, 0x22, 0xb8, 0x38, 0x39, 0x74, 0x92, 0x5c,
	0xae, 0x52, 0x37, 0xa7, 0xbc, 0xef, 0xf3, 0xfc, 0xde, 0x87, 0x87, 0x8b, 0x59, 0x9d, 0x71, 0x16,
	0xb1, 0x57, 0x8b, 0x70, 0x11, 0xb6, 0xe5, 0x68, 0x95, 0x78, 0x20, 0xea, 0x2d, 0xea, 0x47, 0x93,
	0xf9, 0xb0, 0x3d, 0x62, 0x81, 0x43, 0x19, 0x65, 0x8e, 0xf4, 0x86, 0xf3, 0xd7, 0x72, 0x93, 0x8b,
	0x9c, 0x8a, 0x9b, 0x7a, 0xef, 0x02, 0xf7, 0x43, 0xc1, 0xa6, 0x98, 0x3b, 0x58, 0x88, 0x39, 0x27,
	0xe3, 0xd6, 0x94, 0x8c, 0x29, 0xe1, 0x4e, 0xf1, 0x69, 0x8d, 0x18, 0x27, 0xce, 0xa2, 0x93, 0x53,
	0x45, 0x8a, 0x1f, 0x0a, 0x15, 0x52, 0xe6, 0xc1, 0x79, 0xbc, 0x2d, 0x5a, 0x71, 0x32, 0x62, 0x7c,
	0xac, 0xc4, 0x87, 0xf1, 0x1d, 0xb3, 0x32, 0x20, 0x42, 0x60, 0x4a, 0x9e, 0x2e, 0x71, 0x30, 0x9b,
	0x12, 0xeb, 0x89, 0x79, 0xe5, 0x49, 0xc6, 0xbe, 0x69, 0x80, 0xe6, 0x75, 0xc7, 0x6a, 0xe7, 0x19,
	0x85, 0xa4, 0x18, 0xb7, 0xb6, 0x3f, 0x22, 0xed, 0x70, 0x44, 0xe0, 0xf4, 0xa1, 0x51, 0x1e, 0x08,
	0x5a, 0xb8, 0x9e, 0x3a, 0xb4, 0x1e, 0x98, 0xc6, 0x40, 0xd0, 0xe7, 0x98, 0xe3, 0xc0, 0x5e, 0x57,
	0x1a, 0xa0, 0xa9, 0xbb, 0x7a, 0x7e, 0xe1, 0xfd, 0x95, 0x15, 0xe2, 0xae, 0x22, 0x22, 0xec, 0x37,
	0x39, 0x52, 0xbe, 0x40, 0xa4, 0x5c, 0x0f, 0x4d, 0xfd, 0x19, 0xc1, 0xff, 0x95, 0xf6, 0xc8, 0x2c,
	0xbd, 0x88, 0xb8, 0x5d, 0x93, 0x85, 0xaf, 0x65, 0x61, 0xd7, 0x0f, 0x31, 0x5f, 0x29, 0x32, 0x77,
	0xbb, 0xf6, 0x3a, 0x46, 0xda, 0x2e, 0x46, 0xe0, 0xd7, 0x47, 0xa4, 0xed, 0x12, 0x04, 0xbe, 0x24,
	0xe8, 0xf7, 0xfb, 0x9f, 0x5f, 0x4b, 0x7d, 0xdd, 0x00, 0xd5, 0xfb, 0x5d, 0xe3, 0x9f, 0xfd, 0xa6,
	0x7f, 0xd7, 0xb0, 0xaa, 0xeb, 0x8a, 0x3b, 0xd9, 0x7f, 0x87, 0x60, 0x97, 0x42, 0xb0, 0x4f, 0x21,
	0x38, 0xa4, 0x10, 0x24, 0x29, 0x04, 0xdf, 0x52, 0xa8, 0xbd, 0xcb, 0xa0, 0x16, 0x67, 0x10, 0x1c,
	0x32, 0xa8, 0x25, 0x19, 0xd4, 0x7e, 0x6c, 0x10, 0x38, 0x6d, 0xd0, 0x3d, 0xf5, 0x9e, 0x6f, 0xb7,
	0x48, 0xf6, 0xff, 0xb4, 0x45, 0xb7, 0x1e, 0xa1, 0xbe, 0x88, 0x08, 0x57, 0xd6, 0xcb, 0xd5, 0x8c,
	0x7c, 0xde, 0xa2, 0xf3, 0xcb, 0xf7, 0x58, 0x18, 0x91, 0x65, 0x34, 0xbc, 0x92, 0xff, 0xe4, 0xf1,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xfc, 0x58, 0xf6, 0x40, 0x02, 0x00, 0x00,
}

func (this *MessageExample) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MessageExample)
	if !ok {
		that2, ok := that.(MessageExample)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.RecordExample.Equal(&that1.RecordExample) {
		return false
	}
	if this.MsgParam != that1.MsgParam {
		return false
	}
	if this.MsgBytes != that1.MsgBytes {
		return false
	}
	return true
}
func (this *MessageExample_Head) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MessageExample_Head)
	if !ok {
		that2, ok := that.(MessageExample_Head)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Str.Equal(&that1.Str) {
		return false
	}
	if this.MsgParam != that1.MsgParam {
		return false
	}
	return true
}

type MessageExample_HeadFace interface {
	Proto() github_com_gogo_protobuf_proto.Message
	GetStr() Binary
	GetMsgParam() uint64
}

func (this *MessageExample_Head) Proto() github_com_gogo_protobuf_proto.Message {
	return this
}

func (this *MessageExample_Head) TestProto() github_com_gogo_protobuf_proto.Message {
	return NewMessageExample_HeadFromFace(this)
}

func (this *MessageExample_Head) GetStr() Binary {
	return this.Str
}

func (this *MessageExample_Head) GetMsgParam() uint64 {
	return this.MsgParam
}

func NewMessageExample_HeadFromFace(that MessageExample_HeadFace) *MessageExample_Head {
	this := &MessageExample_Head{}
	this.Str = that.GetStr()
	this.MsgParam = that.GetMsgParam()
	return this
}

type MessageExampleHead MessageExample_HeadFace
type MessageExample_Head MessageExample

func (m *MessageExample) AsHead() *MessageExample_Head {
	return (*MessageExample_Head)(m)
}

func (m *MessageExample) AsHeadFace() MessageExampleHead {
	return (*MessageExample_Head)(m)
}

func (m *MessageExample_Head) AsMessageExample() *MessageExample {
	return (*MessageExample)(m)
}

func (m *MessageExample) SetupContext(ctx MessageContext) error {
	if err := ctx.MsgRecord(m, 17, &m.RecordExample); err != nil {
		return err
	}
	return ctx.Message(m, 999999990)
}

func (*MessageExample) GetDefaultPolymorphID() uint64 {
	return 999999990
}

func (m *MessageExample) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessageExample) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MessageExample) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l, fieldEnd int
	_, _ = l, fieldEnd
	if len(m.MsgBytes) > 0 {
		i -= len(m.MsgBytes)
		copy(dAtA[i:], m.MsgBytes)
		i = encodeVarintProtoVnvn(dAtA, i, uint64(len(m.MsgBytes)))
		i--
		dAtA[i] = 0x70
		i--
		dAtA[i] = 0xca
	}
	if m.MsgParam != 0 {
		i = encodeVarintProtoVnvn(dAtA, i, uint64(m.MsgParam))
		i--
		dAtA[i] = 0x70
		i--
		dAtA[i] = 0xc0
	}
	{
		size, err := m.RecordExample.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintProtoVnvn(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x8a
	i = encodeVarintProtoVnvn(dAtA, i, uint64(999999990))
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x80
	return len(dAtA) - i, nil
}

func (*MessageExample_Head) GetDefaultPolymorphID() uint64 {
	return 999999990
}

func (m *MessageExample_Head) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessageExample_Head) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MessageExample_Head) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l, fieldEnd int
	_, _ = l, fieldEnd
	if m.MsgParam != 0 {
		i = encodeVarintProtoVnvn(dAtA, i, uint64(m.MsgParam))
		i--
		dAtA[i] = 0x70
		i--
		dAtA[i] = 0xc0
	}
	{
		size, err := m.Str.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		if size > 0 {
			i -= size
			i = encodeVarintProtoVnvn(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xaa
		}
	}
	i = encodeVarintProtoVnvn(dAtA, i, uint64(999999990))
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x80
	return len(dAtA) - i, nil
}

func encodeVarintProtoVnvn(dAtA []byte, offset int, v uint64) int {
	offset -= sovProtoVnvn(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func init() {
	RegisterMessageType(999999990, "", (*MessageExample)(nil))
	RegisterMessageType(999999990, "Head", (*MessageExample_Head)(nil))
}

func (m *MessageExample) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 2 + sovProtoVnvn(999999990)
	l = m.RecordExample.ProtoSize()
	n += 2 + l + sovProtoVnvn(uint64(l))
	if m.MsgParam != 0 {
		n += 2 + sovProtoVnvn(uint64(m.MsgParam))
	}
	l = len(m.MsgBytes)
	if l > 0 {
		n += 2 + l + sovProtoVnvn(uint64(l))
	}
	return n
}

func (m *MessageExample_Head) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 2 + sovProtoVnvn(999999990)
	if l = m.Str.ProtoSize(); l > 0 {
		n += 2 + l + sovProtoVnvn(uint64(l))
	}
	if m.MsgParam != 0 {
		n += 2 + sovProtoVnvn(uint64(m.MsgParam))
	}
	return n
}

func sovProtoVnvn(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProtoVnvn(x uint64) (n int) {
	return sovProtoVnvn(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MessageExample) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtoVnvn
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessageExample: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessageExample: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordExample", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtoVnvn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtoVnvn
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProtoVnvn
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RecordExample.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 1800:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgParam", wireType)
			}
			m.MsgParam = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtoVnvn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgParam |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 1801:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgBytes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtoVnvn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProtoVnvn
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProtoVnvn
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgBytes = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProtoVnvn(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProtoVnvn
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProtoVnvn
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessageExample_Head) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtoVnvn
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Head: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Head: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Str", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtoVnvn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtoVnvn
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProtoVnvn
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Str.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 1800:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgParam", wireType)
			}
			m.MsgParam = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtoVnvn
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgParam |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProtoVnvn(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProtoVnvn
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProtoVnvn
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProtoVnvn(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProtoVnvn
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProtoVnvn
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProtoVnvn
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProtoVnvn
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProtoVnvn
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProtoVnvn
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProtoVnvn        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProtoVnvn          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProtoVnvn = fmt.Errorf("proto: unexpected end of group")
)
