FROM tsovak/golang
RUN mkdir -p /go/src/github.com/insolar/assured-ledger/ledger-core/v2
WORKDIR /go/src/github.com/insolar/assured-ledger/ledger-core/v2
ENV BIN_DIR="/go/bin"
ENV CGO_ENABLED=1
ENV GOOS=linux
ENV INSOLAR_LOG_LEVEL=debug
ENV INSOLAR_LOG_FORMATTER=text
