---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers: []
  name: database-heavy-0
  namespace: insolar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2G"
