@startuml
Init : stepMigrate
Init -[#blue]-> stepMigrate
Init --> stepGetState : Jump
Init --> [*]
Init --> [*]
stepMigrate : INHERITED
stepMigrate --> stepFinalize : Jump
stepMigrate --> [*]
stepGetState : INHERITED
stepGetState : stepMigrate
stepGetState -[#blue]-> stepMigrate
stepGetState --> stepGotState : Jump
stepGetState --> stepSendStateRequest : Jump
stepGetState --> stepGetState : ThenRepeat
stepFinalize : INHERITED
stepGotState : INHERITED
stepGotState : stepMigrate
stepGotState -[#blue]-> stepMigrate
stepGotState --> stepReadyToWork : Jump
stepSendStateRequest : INHERITED
stepSendStateRequest : stepMigrate
stepSendStateRequest -[#blue]-> stepMigrate
stepSendStateRequest --> stepWaitState : Jump
stepReadyToWork : INHERITED
stepReadyToWork : stepMigrate
stepReadyToWork -[#blue]-> stepMigrate
stepReadyToWork --> stepWaitIndefinitely : Jump
stepWaitState : INHERITED
stepWaitState : stepMigrate
stepWaitState -[#blue]-> stepMigrate
stepWaitState --> stepGotState : Jump
stepWaitState --> stepWaitState : ThenRepeat
stepWaitIndefinitely : INHERITED
stepWaitIndefinitely : stepMigrate
stepWaitIndefinitely -[#blue]-> stepMigrate
stepWaitIndefinitely --> stepWaitIndefinitely : ThenRepeat
@enduml
