@startuml
state "Init" as T00_S001
T00_S001 : StateMachineCallRequest
[*] --> T00_S001
T00_S001 --> T00_S003 : Migrate: s.cancelOnMigrate
state "cancelOnMigrate" as T00_S002
T00_S002 : StateMachineCallRequest
T00_S002 --> T00_S010 : Migrate: <nil>
state "s.objInfo.ContractRunner" as T00_S004 <<sdlreceive>>
T00_S004 : DUPLICATE
state "sendReplyOnCancel" as T00_S010
T00_S010 : StateMachineCallRequest
T00_S010 --> [*]
state "stateDoneImmutableCall" as T00_S007
T00_S007 : StateMachineCallRequest
T00_S007 --[dotted]> T00_S002
state "stateGetSharedReadyToWork" as T00_S003
T00_S003 : StateMachineCallRequest
T00_S003 --[dotted]> T00_S002
T00_S003 --[dashed]> T00_S003 : [smachine.NotPassed]\n[...&&(...).AcquireForThisStep().IsNotPassed()]...\nWaitShared, Sleep
T00_S003 --> [*] : [smachine.Impossible]
T00_S003 --> T00_S004 : PrepareAsync(ctx)
T00_S003 --[dashed]> T00_S005 : Sleep
state "statePrepareMutableCall" as T00_S009
T00_S009 : StateMachineCallRequest
T00_S009 --[dotted]> T00_S002
state "stateRegisterSagaCall" as T00_S008
T00_S008 : StateMachineCallRequest
T00_S008 --[dotted]> T00_S002
state "stateSharedReadyToWork" as T00_S005
T00_S005 : StateMachineCallRequest
T00_S005 --[dotted]> T00_S002
T00_S005 --> T00_S009 : [ContractCallMutable]
T00_S005 --> T00_S006 : [ContractCallImmutable]
T00_S005 --> T00_S008 : [ContractCallSaga]
state "stateStartImmutableCall" as T00_S006
T00_S006 : StateMachineCallRequest
T00_S006 --[dotted]> T00_S002
T00_S006 --[dashed]> T00_S006 : [!ctx.AcquireForThisStep()]\nSleep
T00_S006 --> T00_S004 : PrepareAsync(ctx)
T00_S006 --[dashed]> T00_S007 : Sleep
@enduml
