apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "placeholder"
generatorOptions:
  disableNameSuffixHash: true
resources:
  - 0-Namespace.yaml
bases:
  - ../manifests
patchesStrategicMerge:
  - nodes-patch.yaml
  - patch-Ingress.yaml
  - patch-wait-script.yaml
images:
  - name: insolar/assured-ledger
    newName: usciregistry.azurecr.io/assured-ledger
    newTag: latest
secretGenerator:
  - name: azurecr
    files:
      - .dockerconfigjson=dockerconfigjson
    type: kubernetes.io/dockerconfigjson
configMapGenerator:
  - name: app-bootstrap
    behavior: replace
    files:
      - run.sh=configuration/bootstrap.sh
