apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "placeholder"
generatorOptions:
  disableNameSuffixHash: true
resources:
  - 0-Namespace.yaml
  - 0-StorageClass-AKS.yaml
bases:
  - ../manifests
patchesStrategicMerge:
  - nodes-patch.yaml
  - patch-Ingress.yaml
  - patch-wait-script.yaml
  - patch-certs-pvc.yaml
images:
  - name: insolar/assured-ledger
    newName: usciregistry.azurecr.io/assured-ledger
    newTag: placeholder
secretGenerator:
  - name: azurecr
    files:
      - .dockerconfigjson=dockerconfigjson
    type: kubernetes.io/dockerconfigjson
configMapGenerator:
  - name: app-bootstrap
    behavior: replace
    files:
      - run.sh=configuration/bootstrap.sh
  - name: bootstrap-yaml
    behavior: replace
    files:
      - bootstrap.yaml=configuration/bootstrap-config.yaml
  - name: pulsar-config
    behavior: replace
    files:
      - pulsard.yaml=configuration/pulsar-config.yaml
  - name: wait-script
    behavior: replace
    files:
      - wait-for-bootstrap.sh=configuration/wait-for-bootstrap.sh
