apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: virtual
spec:
  template:
    spec:
      imagePullSecrets:
        - name: azurecr
      containers:
        - name: insolar
          resources:
            limits:
              cpu: "1930m"
              memory: 1Gi
            requests:
              cpu: "1930m"
              memory: 1Gi
