@startuml
Init : INHERITED
Init --> stepRegisterBargeIn : Jump
stepRegisterBargeIn : INHERITED
stepRegisterBargeIn --> stepSendRequest : JumpExt
stepRegisterBargeIn -[#DarkGreen]-> migrateBeforeSendRequest : JumpExt+(StepMigration)
stepSendRequest : INHERITED
migrateBeforeSendRequest : INHERITED
migrateBeforeSendRequest --> stepRegisterBargeIn : Jump
@enduml
