@startuml
state "Init" as T00_S002
T00_S002 : SMTestAPICall
[*] --> T00_S002
T00_S002 --> T00_S003
state "migrationDefault" as T00_S001
T00_S001 : SMTestAPICall
T00_S001 --[dotted]> T00_S001
T00_S001 --> T00_S004
state "stepProcessResult" as T00_S005
T00_S005 : SMTestAPICall
T00_S005 --[dotted]> T00_S001
T00_S005 -->[*]
state "stepRegisterBargeIn" as T00_S003
T00_S003 : SMTestAPICall
T00_S003 --[dotted]> T00_S001
T00_S003 -->[*] : [!(...).PublishGlobalAliasAndBargeIn()]\nError
T00_S003 --> T00_S004
state "stepSendRequest" as T00_S004
T00_S004 : SMTestAPICall
T00_S004 --[dotted]> T00_S001
T00_S004 --> T00_S005 : Sleep
@enduml
