#coverage:
#  range: "50...80"
ignore:
  - "**/*_mock.go"
  - "**/*_string.go"
  - "**/*.pb.go"
fixes:
  - "github.com/insolar/assured-ledger/::"
# see https://docs.codecov.io/docs/pull-request-comments
comment:
  layout: "reach, diff, flags, files"
  behavior: default
