# 1) build step (approx local build time ~4m w/o cache)
ARG GOLANG_VERSION=1.14
FROM golang:${GOLANG_VERSION} AS build

ADD . /go/src/github.com/insolar/assured-ledger
WORKDIR /go/src/github.com/insolar/assured-ledger

# pass build variables as arguments to avoid adding .git directory
ARG BUILD_NUMBER
ARG BUILD_DATE
ARG BUILD_TIME
ARG BUILD_HASH
ARG BUILD_VERSION
# build step
RUN GOPROXY=https://proxy.golang.org,https://goproxy.io,direct \
    make vendor
RUN BUILD_NUMBER=${BUILD_NUMBER} \
    BUILD_DATE=${BUILD_DATE} \
    BUILD_TIME=${BUILD_TIME} \
    BUILD_HASH=${BUILD_HASH} \
    BUILD_VERSION=${BUILD_VERSION} \
    make build