name: long-funcs # long funcs
on:
  schedule:
    - cron: '0 14 * * *'
env:
  KUBECONFIG: k3s.yaml
  GO_VERSION: 1.14
  CI_GOMAXPROCS: 0
  INSOLAR_LOG_LEVEL: warn
jobs:
  long-tests-on-master:
    name: master-long-funcs
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/assured-ledger/assured-ledger/go
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          path: go/src/github.com/insolar/assured-ledger
      - name: Set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Install Protoc
        uses: arduino/setup-protoc@master
      - name: Add bin to path
        run: echo "::add-path::${{env.GOPATH}}/bin"
      - name: Fetch vendor and check succesful build
        run: |
          go mod download
          make vendor install-build-tools pre-build proto build
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/assured-ledger/ledger-core
      - name: Check if working directory is clean after build
        if: always()
        run: scripts/gitstatus.sh -v
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/assured-ledger/ledger-core
      - name: Run unit and slow tests and check code coverage
        if: always()
        run: make test_slow_long
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/assured-ledger/ledger-core
      - name: Run extended tests
        if: always()
        run: make test_extended
        working-directory: ${{env.GOPATH}}/src/github.com/insolar/assured-ledger/ledger-core
      - name: Upload integration_extended_test.log to artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: integration_extended_test_master
          path: ${{env.GOPATH}}/src/github.com/insolar/assured-ledger/ledger-core/integration_extended_test.log
      - name: Send failure notification to Slack
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTIONS_NOTIFICATIONS_SLACK_HOOK_URL }}
