name: SonarQube

on:
  push:
    branches:
    - master

jobs:
  sonar:
    name: Sonar
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: run sonar-scanner
      run: |
        projectKey=$(echo "${{ github.repository }}" | sed 's,/,:,g')
        docker run \
          --rm \
          -v $(pwd):/usr/src \
          sonarsource/sonar-scanner-cli:4.5 \
            -Dsonar.projectKey="${projectKey}" \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
